### ISSUE TITLE
Google 

### ISSUE THREAD

**Issue by Mohadm58** [vamsi3/screen-translator#6] opened 2023-04-03 19:33 UTC
You can add better google. Install google lens Because Google search uses Google lens, I hope you understand 
![IMG_20230403_202931](https://user-images.githubusercontent.com/68702788/229608807-03a92aac-3370-48a2-aa91-eee63a60d1eb.jpg)

**Comment by vamsi3** [comment] 2023-04-05 15:19
Duplicate of #4

**Closed by vamsi3** 2023-04-05 15:19 UTC
